config/routes.rb
CCBCWebsite::Application.routes.draw do
  resources :bookalawns

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: :get
  devise_for :users
  resources :newsletters

  resources :programme2013s

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'ccbc_core#home'
  match "/about", :to => 'ccbc_core#about', via: :get
  match "/howtojoin", :to => 'ccbc_core#howtojoin', via: :get
  match "/whatyouneed", :to => 'ccbc_core#whatyouneed', via: :get
  match "/clubmatters", :to => 'ccbc_core#clubmatters', via: :get
  match "/howtogetthere", :to => 'ccbc_core#howtogetthere', via: :get
  match "/linkstocroquetsites", :to => 'ccbc_core#linkstocroquetsites', via: :get
  

  

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  
  mount_uploader :pdf, PdfUploader
end

app/controllers/newsletters_controller.rb
class NewslettersController < InheritedResources::Base
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @title = "Newsletters"
    # The following line retrieves the newsletters from the database table using a GROUP_BY and ORDER_BY ... DESC SQL query so the elements are grouped by year in a descending order.
    @newsletters = Newsletter.all(:group =>'date', :order =>'date DESC')
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @newsletter }
      else
        format.html { render action: 'new' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:title, :pdf, :date)
    end
  before_filter :authenticate_admin_user!, :except => [:index, :show]
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_for @newsletter, :html => {:multipart => true} do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
<div class="field">
  <%= f.date_select :date %>
</div>
<div class="field">
  <%= f.file_field :pdf %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<h1>Listing Newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th> 
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= link_to newsletter.title, newsletter.pdf_url %></td>
        <td><%= newsletter.date.year%></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @newsletter.title %>
</p>
<p>
  <strong>Date:</strong>
  <%= @newsletter.date %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>