config/routes.rb
CCBCWebsite::Application.routes.draw do
  resources :bookalawns

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: :get
  devise_for :users
  resources :newsletters

  resources :programme2013s

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'ccbc_core#home'
  match "/about", :to => 'ccbc_core#about', via: :get
  match "/howtojoin", :to => 'ccbc_core#howtojoin', via: :get
  match "/whatyouneed", :to => 'ccbc_core#whatyouneed', via: :get
  match "/clubmatters", :to => 'ccbc_core#clubmatters', via: :get
  match "/howtogetthere", :to => 'ccbc_core#howtogetthere', via: :get
  match "/linkstocroquetsites", :to => 'ccbc_core#linkstocroquetsites', via: :get
  

  

end

app/models/bookalawn.rb
class Bookalawn < ActiveRecord::Base
  has_event_calendar
end

app/controllers/bookalawns_controller.rb
class BookalawnsController < InheritedResources::Base
   before_action :require_login
   before_action :set_bookalawn, only: [:show, :edit, :update, :destroy]

  # GET /bookalawns
  # GET /bookalawns.json
  def index
    @title = "Book a Lawn"
    @bookalawns = Bookalawn.all
    
     @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Bookalawn.event_strips_for_month(@shown_month)
    
  end

  # GET /bookalawns/1
  # GET /bookalawns/1.json
  def show
  end

  # GET /bookalawns/new
  def new
    @bookalawn = Bookalawn.new
  end

  # GET /bookalawns/1/edit
  def edit
  end

  # POST /bookalawns
  # POST /bookalawns.json
  def create
    @bookalawn = Bookalawn.new(bookalawn_params)

    respond_to do |format|
      if @bookalawn.save
        format.html { redirect_to @bookalawn, notice: 'Booking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookalawn }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookalawn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookalawns/1
  # PATCH/PUT /bookalawns/1.json
  def update
    respond_to do |format|
      if @bookalawn.update(bookalawn_params)
        format.html { redirect_to @bookalawn, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookalawn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookalawns/1
  # DELETE /bookalawns/1.json
  def destroy
    @bookalawn.destroy
    respond_to do |format|
      format.html { redirect_to bookalawns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookalawn
      @bookalawn = Bookalawn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookalawn_params
      params.require(:bookalawn).permit(:lawn, :start_at, :end_at)
    end
end

app/helpers/bookalawns_helper.rb
module BookalawnsHelper

  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
  
end

app/views/bookalawns/_form.html.erb
<%= form_for(@bookalawn) do |f| %>
  <% if @bookalawn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookalawn.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @bookalawn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lawn %><br>
    <%= f.select :lawn, options_for_select([["Please Select", "Lawn A"], "Lawn A", "Lawn B", "Lawn C", "Lawn D"]) %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Booking' %>
  </div>
<% end %>

app/views/bookalawns/edit.html.erb
<h1>Editing a booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookalawn %> |
<%= link_to 'Back', bookalawns_path %>

app/views/bookalawns/index.html.erb
<%= javascript_include_tag 'event_calendar' %>
<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Lawn</th>
      <th>Start at</th>
      <th>End at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookalawns.each do |bookalawn| %>
      <tr>
        <td><%= bookalawn.lawn %></td>
        <td><%= bookalawn.start_at %></td>
        <td><%= bookalawn.end_at %></td>
        <td><%= link_to 'Show', bookalawn %></td>
        <td><%= link_to 'Edit', edit_bookalawn_path(bookalawn) %></td>
        <td><%= link_to 'Destroy', bookalawn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_bookalawn_path %>

<br>
<br>

<%= stylesheet_link_tag "event_calendar" %>


<%= raw(event_calendar) %>

app/views/bookalawns/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookalawns_path %>

app/views/bookalawns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lawn:</strong>
  <%= @bookalawn.lawn %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @bookalawn.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @bookalawn.end_at %>
</p>

<%= link_to 'Edit', edit_bookalawn_path(@bookalawn) %> |
<%= link_to 'Back', bookalawns_path %>