config/routes.rb
CCBCWebsite::Application.routes.draw do
  resources :bookalawns

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: :get
  devise_for :users
  resources :newsletters

  resources :programme2013s

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'ccbc_core#home'
  match "/about", :to => 'ccbc_core#about', via: :get
  match "/howtojoin", :to => 'ccbc_core#howtojoin', via: :get
  match "/whatyouneed", :to => 'ccbc_core#whatyouneed', via: :get
  match "/clubmatters", :to => 'ccbc_core#clubmatters', via: :get
  match "/howtogetthere", :to => 'ccbc_core#howtogetthere', via: :get
  match "/linkstocroquetsites", :to => 'ccbc_core#linkstocroquetsites', via: :get
  

  

end

app/views/layouts/_footer.html.erb
<footer>
  &copy; <%= Time.now.year %> Cheam Croquet and Bowls Club 
</footer> 

app/views/layouts/_header.html.erb
<header>
  
  <%= image_tag("ccbc_logo.gif", :alt => "logo") %>

  <h2>CHEAM CROQUET AND BOWLS CLUB</h2>
 </header>

app/views/layouts/_navigation.html.erb
<nav id="menu">
  <ul>
    <li><%=link_to "Home", root_path %> </li>
    <li><%=link_to "About", about_path %> </li>
    <li><%=link_to "How To Join", howtojoin_path %> </li>
    <li><%=link_to "What You Need", whatyouneed_path %> </li>
    <li><%=link_to "Programme 2013", programme2013s_path %> </li>
    <li><%=link_to "Newsletters", newsletters_path %> </li>
    <li><%=link_to "Club Matters", clubmatters_path %> </li>
    <li><%=link_to "How To Get There", howtogetthere_path %> </li>
    <li><%=link_to "Book A Lawn", bookalawns_path %> </li>
    <li><%=link_to "Links to Croquet Sites" %> 
    <nav id="menu">
  <ul>
    <li> <%=link_to "The Croquet Association" %>
    <nav id="menu">
    <ul>
      <li><%=link_to "CA Home", "http://www.croquet.org.uk/" %></li>
      <li><%=link_to "CA Events","http://www.croquet.org.uk/tournament/" %></li>
    </ul>
    </nav>
    </li>
    <li> <%=link_to "SECF", "http://www.southeastcroquet.org.uk/" %></li>
    <li> <%=link_to "Croquet Academy", "http://www.thecroquetacademy.com/" %></li>
    <li> <%=link_to "Croquet Equipment" %>
    <nav id="menu">
    <ul>
      <li><%=link_to "Mallets etc.", "http://www.oxfordcroquet.com/equip/" %></li>
      <li><%=link_to "Whites","http://www.bowlsdirect.com/contact.htm" %></li>
    </ul>
    </nav>
    </li>
    <li> <%=link_to "Croquet Glossary", "http://cornwall-croquet.org.uk/croquet_glossary.htm" %></li>
    <li> <%=link_to "Croquet Rules"%>
      <nav id="menu">
    <ul>
      <li><%=link_to "Association Rules", "http://www.croquet.org.uk/association/laws.html" %></li>
      <li><%=link_to "Golf Rules","http://www.croquet.org.uk/golf/laws/contents.htm" %></li>
    </ul>
    </nav>
    </li>
  </ul>
</nav>
    </li>
  </ul>
</nav>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF=8">
  <title><%= title %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <%= render 'layouts/header' %>
  <%= render 'layouts/navigation' %>
  <div id="container">
    <%= yield %>
  </div>
  <div id="logstat">
  <%= render 'layouts/user_widget' %>
  </div> 
  <%= render 'layouts/footer' %>
   

</body>

</html>